### ISSUE TITLE
Remap Forge into Yarn mappings

### ISSUE THREAD

**Issue by ramidzkh** [liachmodded/talk#10]
@liach
You asked me to remind you on your talk page.
Also, I've never used Forge before so I have no idea now stuff works :smiley:

**Comment by liach** [comment]
I know it's not serious, but trying this out will probably allow me to improve my skills working on the toolchains of fabric, forge, etc.

**Comment by liach** [comment]
Guess we can use https://github.com/patchworkmc/yarnforge for now
