### ISSUE TITLE
General question about Github Packages usage

### ISSUE THREAD

**Issue by briantsai-lils** [liachmodded/talk#11]
@liach Hi, I am testing publishing packages to Github.  The publish is successful but running into issues installing/resolving the packages on the consumer end.  Looking for someone who has done this to pick their brain.  If you are able to help please let me know.  Thanks!

**Comment by liach** [comment]
Installing GitHub packages requires an OAuth token with read package access. fairly weird, but that's what github asks for.

**Comment by briantsai-lils** [comment]
My problems were caused by issues both on my side and github. I've fixed my syntax errors, but on github seems there are limited feature support for what I need (no SNAPSHOT and dynamic versioning support) so I am looking at alternate maven hosts.   Thanks for your response, will close this.

**Comment by liach** [comment]
yep. you can choose bintray, which has a similar bandwidth and storage limit compared to github packages; bintray accepts multiple artifacts with different classifiers; finally, you can request your package be included in jcenter or maven central.
