### ISSUE TITLE
你好，请问能帮忙review一个翻译更新的pr么？

### ISSUE THREAD

**Issue by Hambaka** [liachmodded/talk#12]
@liach
我不是很清楚是否应该使用Discord联系你，所以尝试用这个方式联系。去年在RC服务器里聊天，你用Jelly的那些优化Mod成功把我带进Fabric的坑（没办法，我的电脑太烂），所以最近我也尝试使用Github给Fabric的Mod做翻译，不过也正因如此，Github的很多功能都不是很熟悉，只是会一点基础的操作。

事情是这样的，我最近给ModMenu更新了一下翻译文件，PR在[这里](https://github.com/Prospector/ModMenu/pull/156)，因为改动的地方有点多，我也不知道找谁讨论，如果能有人讨论的话就能进行更多修改，最终达成令人满意的翻译质量，因为我认为ModMenu还是Fabric侧很重要的一个Mod，使用人数很多，所以在PR里写了很多给中文译者看的文字，方便之后讨论修改。我是希望在下次更新前能完善翻译并顺利合并。

因为看到你以前有review过别人给ModMenu更新的语言文件，我就想过来问问能否帮忙看一下，虽然我还有给别的Mod开的pr等待review，但是ModMenu是最重要的一个，而且可能这些方面的词汇你比我更熟悉，我一是怕搞砸，二是实在不知道能找谁帮忙review…… 

如果能帮忙review的话，我先提前说声谢谢，如果有修改意见我也会即时修正翻译的。

**Comment by liach** [comment]
嗯，内容不错。记得3TUSK（us knowledge）好像搞了套翻译标准，你可以去看看，比如数字/英文和中文混用连接的地方加空格之类的

**Comment by Hambaka** [comment]
采纳了修改建议，关于空格问题，我不是很清楚3TUSK是否发过，也不知道上哪找，但是他参与了i18n，所以我参考了i18n/cfpa的这个[Minecraft 模组简体中文翻译规范与指南](https://rules.cfpa.team/)，对比了一下之后就修改了数字部分的空格。

**Comment by liach** [comment]
好像就是这个文档
