### ISSUE TITLE
81k

### ISSUE THREAD

**Issue by Technici4n** [liachmodded/talk#14]
Hello @liach, do you really think we can reasonably enforce a fabric-wide fixed denominator of 81k after 2 years of debate? (honest question)
The main issue is see is the fluid stuck in pipes thing, when it comes to the api it just involves adding `1`s or `81000`s here and there, which I feel is no big deal.

**Comment by liach** [comment]
Imo for the fluid api, as long as you convert the rest of the operations into whole number than lossy double after chosing the 81000 as the universal numerator, it should be good enough. You can just add public static final fields for whether to add 1s or 81000s, like `int BUCKET = 81000;` or `int SOURCE_BLOCK = 81000;`, `int GLASS_BOTTLE = 27000`, `int MILIBUCKET = 81;`, `int NUGGET = 1000` etc. (likely in an interface)

If people need to transport fluid in another base denominator, like in 1/7 of a block, with the basic lookup/transportation api they can declare another type of transportation for accurate transportation and implement custom conversions themselves, like keeping a fraction calculator with `81000 * 7` at the converter so the converter will keep the modulo flow to themselves and potentially add to future flow than causing some floating-point precision loss.

**Comment by Technici4n** [comment]
Updated the PR, thanks for your input.
