### ISSUE TITLE
Talk?

### ISSUE THREAD

**Issue by YanisBft** [liachmodded/talk#16]
Hi @liach, any way available to talk to you privately?

**Comment by liach** [comment]
Sorry, but did I just caused another round of drama in fabricord?

**Comment by YanisBft** [comment]
Not afaik, I just want to talk with you about the whole situation

**Comment by liach** [comment]
Can I send an email to your email (as seen on github commits, which your pr review suggestions use?)?

**Comment by YanisBft** [comment]
yes you can

**Comment by liach** [comment]
Thanks yanis. Hope you are all good! :heart:
