### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by rogue-agent** [liachmodded/talk#18]
@liach

Hello there.
I'm trying to contact your colleague and friend Dockter regarding Spoutcraft. I'm the Project leader of Abyss CS and we have been developing our Nostalgic 1.2.5 Minecraft server for some time now. We are interested in bringing back elements from Spoutcraft to give it some more flavour. I've found a Spoutcraft launcher, but it does not work properly as the Backend for spout.in does not, well, exist or it does but it is not reachable. 

In cooperation with Wooden3 Studios, we'd be developing our minecraft scape. 

I've tried to reach out to Mr. Dockter but the website is down or I can't reach it, the Teamspeak server almura.enjinvoice.com is well empty and there are no other clues out in the web.

I'm trying to find a working version of Spoutcraft 1.2.5 as mod and maybe if possible a complete launcher with mod and minecraft pack in 1.5.2 or 1.4.7.

Best Regards
Thomas from Abyss
admin@abyss.fi

**Comment by liach** [comment]
I suggest you contacting zidane and dockter from spongpowered discord or forums (or like zidane at spongepowered.org). They were the developers of spoutcraft I think.

Unfortunately, I have never been associated with spoutcraft, so the way to contact them is the best I can help.
