### ISSUE TITLE
Inquiry regarding Snowman

### ISSUE THREAD

**Issue by 3TUSK** [liachmodded/talk#19]
@liach
希望你还记得 3TUSK 这个 ID。这次我代表 TeaCon 茶后谈编辑部前来求证一个事情：那个据说是来方便 Modder 做反混淆表的 Snowman 项目。
TeaCon 茶后谈是 TeaCon 的周边项目，致力于「收集 Modded Minecraft 社区中有趣的冷知识、重要历史事件和一切有记录价值的事物」，形式上类似于自媒体，载体目前是 B 站专栏，并在我们自己的网站上有归档。
具体来说，我想问这些问题：

  1. 这个项目是不是在 [https://github.com/SpongePowered/Snowman](https://github.com/SpongePowered/Snowman)？
  2. 这个项目最初是谁创立的？在什么时候创立的？
  3. 这个项目是基于 ForgeGradle 的 patcher project 吗？
  4. 这个项目目前还在使用吗？过去和现在的主要的用途是什么？
  5. 这个项目的访问权限是邀请制的吗？现在还开放邀请吗？

感谢你的答复！

此致
3TUSK

**Comment by liach** [comment]
snowman 仓库链接正确（我现在看不到，可能被踢了），可以问 kashike 申请看。应该是他成立的，具体时间不知道了。
它就是 mcp 名称的 minecraft 源代码，方便查看（比如手机上看），不是 mapping 数据。记得不开源唯一原因是为了遵守 minecraft eula，不然会吃 DMCA takredown。有没有使用 forgegradle 构建也记不得了 😅 
snowman 名称来源应该大家都知道，是因为 mojang 
1.8 某个版本开始，混淆后所有 parameter name 都是一个 unicode 雪人符号。
因为我已经看不到这个仓库了，所以需要具体看仓库的答案我难以回答。推荐具体要看仓库的问题找 kashike，他应该不难说话。有更多问题或者别的细节想问我也可以。

**Comment by 3TUSK** [comment]
> 我已经看不到这个仓库了

从 zml 那里得知这个仓库已经不再使用了，大概率已经删除了。

感谢回复！
