### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by TPC25** [liachmodded/talk#3]
I'm new to github and trying to learn how to work around with the website. I have been keeping track of Railcraft for a while and was wondering if there is a way I can download RC for 12.2 to test things out and help report issue about the mod. I notice other people has been testing it out and I'm not sure if they are members of you guys or just normal players helping out with testing. If I am able to download it, where do I go to get it? Hope to hear from you and thanks.

**Comment by liach** [comment]
You should install jdk 8 and git on your computer.
Then open command prompt and run `git clone https://github.com/Railcraft/Railcraft --recursive`
go to the railcraft directory, find railcraft.java and delete a block that listens to finger print errors
and then do `gradle build`
