### ISSUE TITLE
Almura content loader crash

### ISSUE THREAD

**Issue by PowellA12** [liachmodded/talk#7]
@liach
I added 42 differnt stairs to almura content but almura keeps crashing
I don't understand why it's crashing 
https://github.com/PowellA12/ServerContent

**Comment by PowellA12** [comment]
[crash-2019-01-26_01.27.08-client.txt](https://github.com/liachmodded/talk/files/2799475/crash-2019-01-26_01.27.08-client.txt)
[techniclauncher_2019-01-24.log](https://github.com/liachmodded/talk/files/2799478/techniclauncher_2019-01-24.log)

**Comment by PowellA12** [comment]
So I compiled my own almura.jar and looks like the same crash
https://gist.github.com/PowellA12/6cab44519dcee9a00508c41c1d75dbd0

**Comment by PowellA12** [comment]
maybe a loading error where loading all stairs last would fix the problem?

**Comment by liach** [comment]
not at all.

**Comment by PowellA12** [comment]
i think the problem comes from the stairs being made from other almura blocks

**Comment by liach** [comment]
dunno

**Comment by PowellA12** [comment]
should i ask k

**Comment by liach** [comment]
hmm, i'd fix the wrong shading first

**Comment by PowellA12** [comment]
shader?

**Comment by liach** [comment]
no. ask on discord instead
