### ISSUE TITLE
Help with entity rendering.

### ISSUE THREAD

**Issue by IbraheemR** [liachmodded/talk#9]
@liach
HI, I'm trying to create a 'hover boat'/Blimp entity. For the moment I'm just trying to create a duplicate of the `BoatEntity`, after which I'll add my specific functionality. I've found your kayak mod's repo a useful reference, but I've been having some issues getting the Renderer to work (the entity is invisible). I was wondering if you could give me a few pointers - what did you go through when creating the renderers for your mod? 

From what I gather the code in your `AbstractBoatEntityRenderer`'s `render` method is more or less the same as the game's internal `BoatEntityRenderer` with the addition of `renderContent` to allow you to show your custom components,

 I'm pretty sure its not an issue with my texture identifier, nor am I getting any obvious errors thrown at Runtime

Thanks for any help!

**Comment by liach** [comment]
mind linking to your code? make sure you register your entity to the entity render dispatcher (through fabric api), though i'd assume something else is more likely to be the cost.

**Comment by IbraheemR** [comment]
The Blimp relevant code is here:
https://github.com/IbraheemR/epicplanes/tree/master/src/main/java/com/ibraheemrodrigues/epicplanes/blimp

I realised I've registered my renderers in a unconventional way - the BlimpEntity registerers the renderer in its clientInit() method (called in MainClient), rather than there being a central client class to register all renderers, as in your KayakClient

**Comment by liach** [comment]
Ah, turns out you need your custom packet or spawning your blimp. you can override `Entity#createSpawnPacket` to create your custom spawn packet or use a mixin on the side where spawn packet is handled to handle your entities (I do the mixin way, see https://github.com/liachmodded/kayak/blob/7423a62df3b6508a3b24626cdf3909ad333687d1/src/main/java/com/github/liachmodded/kayak/mixin/client/ClientPlayNetworkHandlerMixin.java#L33)

**Comment by IbraheemR** [comment]
Thanks, I’ll text it when I get home.

Does this mean that the entity excuses on the server, so physics is calculated etc. But the client has no idea about it and so does not render nor let me me interact?

Why does this happen in this case but not with the Creeper varient I also created? (I assume the packet is handled by LivingEntity or some other superclass that my BlimpEntity does not handle)

**Comment by liach** [comment]
yes, living entities has a mod compatible packet, while other entities don't. since the entity doesn't exist on the client, you can't interact or see hitbox but may experience like bounce back if you walk into the blimp's hitbox

**Comment by IbraheemR** [comment]
Thanks a lot, it all works now!
